
CREATE TABLE "BOOK" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"BOOK_TITLE"	NVARCHAR2(50)		NOT NULL,
	"BOOK_WRITER"	NVARCHAR2(20)		NOT NULL,
	"BOOK_PRICE"	NUMBER		NOT NULL,
	"REG_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "BOOK"."BOOK_NO" IS '책 번호(PK)';

COMMENT ON COLUMN "BOOK"."BOOK_TITLE" IS '책 제목';

COMMENT ON COLUMN "BOOK"."BOOK_WRITER" IS '글쓴이';

COMMENT ON COLUMN "BOOK"."BOOK_PRICE" IS '가격';

COMMENT ON COLUMN "BOOK"."REG_DATE" IS '등록일';

ALTER TABLE "BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (
	"BOOK_NO"
);

COMMIT;


SELECT * FROM "BOOK";

CREATE SEQUENCE SEQ_BOOK_NO NOCACHE;

INSERT INTO "BOOK" VALUES 
	(SEQ_BOOK_NO.NEXTVAL,'셜록 홈즈','아서 코난 도일',20000,DEFAULT);
INSERT INTO "BOOK" VALUES 
	(SEQ_BOOK_NO.NEXTVAL,'DB구현','교육부',10000,DEFAULT);

SELECT BOOK_NO,BOOK_TITLE ,BOOK_WRITER ,BOOK_PRICE,TO_CHAR(REG_DATE,'YYYY-MM-DD') REG_DATE
FROM "BOOK" ORDER BY BOOK_NO ;

DELETE FROM "BOOK" WHERE BOOK_TITLE='책';


UPDATE "BOOK" 
	SET BOOK_PRICE = 1234 
	WHERE BOOK_NO=15;

-----------------------------------------------------------------------------
-- TB_USER 테이블 생성 및 SEQ_UNO 시퀀스 생성

CREATE TABLE TB_USER(

USER_NO NUMBER PRIMARY KEY,

USER_ID VARCHAR2(50) UNIQUE NOT NULL,

USER_NAME VARCHAR2(50) NOT NULL,

USER_AGE NUMBER NOT NULL

);

CREATE SEQUENCE SEQ_UNO;

-- 샘플 데이터 삽입

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'gd_hong', '홍길동', 20);

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'sh_han', '한소희', 28);

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'jm_park', '지민', 27);

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'jm123', '지민', 25);

SELECT * FROM TB_USER;

COMMIT;


SELECT count(*)
FROM TB_USER
WHERE USER_ID = 'gd_hong';

------------------------------------------------------------------------------


CREATE TABLE CUSTOMER(

CUSTOMER_NO NUMBER PRIMARY KEY,

CUSTOMER_NAME VARCHAR2(60) NOT NULL,

CUSTOMER_TEL VARCHAR2(30) NOT NULL,

CUSTOMER_ADDRESS VARCHAR2(200) NOT NULL

);

CREATE SEQUENCE SEQ_CUSTOMER_NO NOCACHE;

SELECT * FROM CUSTOMER;






